### ISSUE TITLE
Comment on API/WebSocketServerClass.md

### ISSUE THREAD

**Issue by mesopelagique** [doc4d/docs#2048]
https://github.com/doc4d/docs/blob/main/docs/API/WebSocketServerClass.md

Please enter your comment:

Missing parenthesis
```4d
$ws.send(Uppercase($message.data)
```

---

I do not understand `wss:=` here

```4d
CALL WORKER("WebSocketServer"; Formula(wss:=4D.WebSocketServer.new($handler)))
```
seems useless in example and overcomplicated

---

in the table that display this
```markdown
WSSHandler | Object | -> | Object of the user class declaring the WebSocket Server callbacks
-- | -- | -- | --
options | Object | -> | WebSocket configuration parameters
```

maybe a link to 
https://doc4d.github.io/docs/next/API/WebSocketServerClass/#options-parameter
or describe here the key because difficult to find it, a lot of scroll to find
or put options table first, before handler

**Comment by arnaud4d** [comment]
fixed missing ), added a comment to enlight the use of wss, added links to parameter descriptions - thanks
